### ISSUE TITLE
Why both npm and yarn lock files?

### ISSUE THREAD

**Issue by lirantal** [darcyclarke/rawkit#33]
Noticed you have lock files of both package managers.
Shouldn't you just stick to one of them?

**Comment by darcyclarke** [comment]
Good catch. I think this was left after some testing with yarn (which I love) but I eventually just stuck with good 'ol npm lock files. I'll remove it.

**Comment by darcyclarke** [comment]
Resolved in: https://github.com/darcyclarke/rawkit/commit/603519442b11b036187975ee1baa8a6b5536bf63
