### ISSUE TITLE
Add npx link

### ISSUE THREAD

**Issue by jantimon** [darcyclarke/rawkit#34]
You might add an npx (included in npm 5.2+) example ;)

```
npx rawkit example.js
```

**Comment by darcyclarke** [comment]
:+1: I like this a lot. I actually used `npx` while finalizing this the last week or so

**Comment by darcyclarke** [comment]
https://github.com/darcyclarke/rawkit/commit/15b90af46f552e8380c81140c640154b87ca8ec0
