### ISSUE TITLE
Use this tool in windows occur a error with auto open the devtools for nodejs context

### ISSUE THREAD

**Issue by safarishi** [darcyclarke/rawkit#44]
* **Version**: 1.1.1
* **Platform**: Windows 7 Professional Edition
* **Chrome Version**: 58.0.3029.110 (64-bit)

## Then I got the error when I start my express server
![error](https://user-images.githubusercontent.com/9312426/29484700-bcdd9002-84f6-11e7-824c-75d92e82a084.png)

**Comment by darcyclarke** [comment]
Hey @safarishi! Thanks for filing this issue. I'll look into Windows debugging when I get a chance later today. I've pushed off a new release because of some breaking changes I've made to how we launch the devtools so any fix for this as well will probably come out Monday/Tuesday.

**Comment by safarishi** [comment]
thanks ~

**Comment by safarishi** [comment]
When I upgrade chrome to 60 the devtools for the chrome has a change,
you can open devtools for nodejs

![image](https://user-images.githubusercontent.com/9312426/29550878-b53eff68-8742-11e7-9955-ba49d68cbd80.png)

Thats so cool

**Comment by darcyclarke** [comment]
This should be fixed as of the `v1.2` release where *rawkit* specifically looks at your operating system and determines which "executable" to use (ie. "google chrome" on Mac, "google-chrome" on Linux & "chrome" on Windows). If you still find you're having issues, definitely let me know.
