### ISSUE TITLE
rawkit causes browser to open the rawkit launch page rather than chrome devtools page

### ISSUE THREAD

**Issue by ballPointPenguin** [darcyclarke/rawkit#77]
* **Version**: 1.3.2
* **Platform**: MINGW64_NT-10.0 WXLPC0HYS9N 2.10.0(0.325/5/3) 2018-02-12 08:49 x86_64 Msys
* **Chrome Version**: Version 66.0.3359.45 (Official Build) beta (64-bit)

whenever I execute `npx rawkit app.js`, my chrome browser responds by opening up a Rawkit Launch page (https://darcyclarke.github.io/rawkit/?url=chrome-devtools) ...
and *not* the chrome-devtools:// page that I am expecting. I have the rawkit extension installed and running in my browser so I don't know why it keeps prompting me to "Click to Add Rawkit to Chrome"

**Comment by darcyclarke** [comment]
Thanks for submitting this issue. I'll look into this today. Potentially try uninstalling and reinstalling the extension; that said, you should never experience that behaviour (there must be an error happening in the extension).

**Comment by ballPointPenguin** [comment]
closing this until/unless I see the behaviour again

**Comment by tokland** [comment]
@ballPointPenguin How did you solve it? It never worked for me, it always redirects to the Rawkit Launch page. rawkit 1.3.2, rawkit chrome extension 1.2.0, Chrome 67.0.3396.87

**Comment by ballPointPenguin** [comment]
@tokland I did not solve it. I have not been using rawkit lately. If you are seeing this or a similar problem, you should re-open this ticket or create a new one.
